TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this

# ========================================
# Install timing/event related databases
# ========================================

# Install Common databases needed by All IOCs
# ========================================================
# Install databases from iocAdmin package
# These databases support IOC Health and Monitoring
# ========================================================
# HardIOC using RTEMS
DB_INSTALLS += $(IOCADMIN)/db/iocAdminRTEMS.db
# SoftIOC
DB_INSTALLS += $(IOCADMIN)/db/iocAdminSoft.db

DB_INSTALLS += $(IOCADMIN)/db/iocAdminScanMon.db
DB_INSTALLS += $(IOCADMIN)/db/iocScanMonSum.db
DB_INSTALLS += $(IOCADMIN)/db/iocScanMon.db
IOCRELEASE_DB += iocRelease.db

DB += agilent4uhv_alias.db
DB += agilent4uhv_alias_df2h.db
DB += gun_agilent4uhv.substitutions 
DB += gun_mks937b.substitutions 
DB += gun-vac.substitutions
DB += l002_agilent4uhv.substitutions 
DB += l002_mks937b.substitutions 
DB += l102_agilent4uhv.substitutions 
DB += l102_mks937b.substitutions 
DB += bc1h_agilent4uhv.substitutions 
DB += bc1h_mks937b.substitutions 
DB += l201_agilent4uhv.substitutions 
DB += l201_mks937b.substitutions 
DB += l202_agilent4uhv.substitutions 
DB += l202_mks937b.substitutions 
DB += l203_agilent4uhv.substitutions 
DB += l203_mks937b.substitutions 
DB += l204_agilent4uhv.substitutions 
DB += l204_mks937b.substitutions 
DB += l205_agilent4uhv.substitutions 
DB += l205_mks937b.substitutions 
DB += l206_agilent4uhv.substitutions 
DB += l206_mks937b.substitutions 
DB += l207_agilent4uhv.substitutions 
DB += l207_mks937b.substitutions 
DB += l208_agilent4uhv.substitutions 
DB += l208_mks937b.substitutions 
DB += l209_agilent4uhv.substitutions 
DB += l209_mks937b.substitutions 
DB += l210_agilent4uhv.substitutions 
DB += l210_mks937b.substitutions 
DB += bc2h_agilent4uhv.substitutions 
DB += bc2h_mks937b.substitutions 
DB += l3a1_agilent4uhv.substitutions 
DB += l3a1_mks937b.substitutions
DB += l3a2_agilent4uhv.substitutions 
DB += l3a2_mks937b.substitutions 
DB += bc3h_agilent4uhv.substitutions 
DB += bc3h_mks937b.substitutions 
DB += df2h_agilent4uhv.substitutions 
DB += df2h_mks937b.substitutions 
DB += hsbl_agilent4uhv.substitutions 
DB += hsbl_mks937b.substitutions 
DB += l3b1_agilent4uhv.substitutions 
DB += l3b1_mks937b.substitutions 
DB += l3b2_agilent4uhv.substitutions 
DB += l3b2_mks937b.substitutions 
DB += l402_agilent4uhv.substitutions 
DB += l402_mks937b.substitutions 
DB += l403_agilent4uhv.substitutions 
DB += l403_mks937b.substitutions 
DB += l404_agilent4uhv.substitutions 
DB += l404_mks937b.substitutions 
DB += l405_agilent4uhv.substitutions 
DB += l405_mks937b.substitutions 
DB += l406_agilent4uhv.substitutions 
DB += l406_mks937b.substitutions 
DB += l407_agilent4uhv.substitutions 
DB += l407_mks937b.substitutions 
DB += l408_agilent4uhv.substitutions 
DB += l408_mks937b.substitutions 
DB += l409_agilent4uhv.substitutions 
DB += l409_mks937b.substitutions 
DB += l410_agilent4uhv.substitutions 
DB += l410_mks937b.substitutions 
DB += l411_agilent4uhv.substitutions 
DB += l411_mks937b.substitutions 
DB += l412_agilent4uhv.substitutions 
DB += l412_mks937b.substitutions 
DB += l413_agilent4uhv.substitutions 
DB += l413_mks937b.substitutions 
DB += l414_agilent4uhv.substitutions 
DB += l414_mks937b.substitutions 
DB += l415_agilent4uhv.substitutions 
DB += l415_mks937b.substitutions 
DB += l416_agilent4uhv.substitutions 
DB += l416_mks937b.substitutions 
DB += l417_agilent4uhv.substitutions 
DB += l417_mks937b.substitutions 
DB += l418_agilent4uhv.substitutions 
DB += l418_mks937b.substitutions 
DB += l419_agilent4uhv.substitutions 
DB += l419_mks937b.substitutions 
DB += l420_agilent4uhv.substitutions 
DB += l420_mks937b.substitutions 
DB += l421_agilent4uhv.substitutions 
DB += l421_mks937b.substitutions 
DB += l422_agilent4uhv.substitutions 
DB += l422_mks937b.substitutions 
DB += l423_agilent4uhv.substitutions 
DB += l423_mks937b.substitutions 
DB += l424_agilent4uhv.substitutions 
DB += l424_mks937b.substitutions 
DB += l425_agilent4uhv.substitutions 
DB += l425_mks937b.substitutions 
DB += l426_agilent4uhv.substitutions 
DB += l426_mks937b.substitutions 
DB += l427_agilent4uhv.substitutions 
DB += l427_mks937b.substitutions 
DB += l428_agilent4uhv.substitutions 
DB += l428_mks937b.substitutions 
DB += hbtl1_agilent4uhv.substitutions 
DB += hbtl1_mks937b.substitutions 
DB += hbtl3_agilent4uhv.substitutions 
DB += hbtl3_mks937b.substitutions 
DB += hu1td_agilent4uhv.substitutions 
DB += hu1td_mks937b.substitutions 
DB += hu23_agilent4uhv.substitutions 
DB += hu23_mks937b.substitutions 
DB += hu89_agilent4uhv.substitutions 
DB += hu89_mks937b.substitutions 
DB += hu1314_agilent4uhv.substitutions 
DB += hu1314_mks937b.substitutions 
DB += hu1920_agilent4uhv.substitutions 
DB += hu1920_mks937b.substitutions 
DB += hu2526_agilent4uhv.substitutions 
DB += hu2526_mks937b.substitutions 
DB += hu1e_agilent4uhv.substitutions 
DB += hu1e_mks937b.substitutions 
DB += l3s_agilent4uhv.substitutions
DB += l3s_mks937b.substitutions
DB += bc3s_agilent4uhv.substitutions
DB += bc3s_mks937b.substitutions
DB += dc1_agilent4uhv.substitutions
DB += dc1_mks937b.substitutions
DB += df2s_agilent4uhv.substitutions
DB += df2s_mks937b.substitutions
DB += su1td_agilent4uhv.substitutions
DB += su1td_mks937b.substitutions
DB += su3_agilent4uhv.substitutions
DB += su3_mks937b.substitutions
DB += su6_agilent4uhv.substitutions
DB += su6_mks937b.substitutions
DB += su12_agilent4uhv.substitutions
DB += su12_mks937b.substitutions
DB += su1e_agilent4uhv.substitutions
DB += su1e_mks937b.substitutions

DB_INSTALLS += $(AGILENT4UHV)/db/agilent4uhv.db
DB_INSTALLS += $(MKS937B)/db/dbMks937bAi.db
DB_INSTALLS += $(MKS937B)/db/dbMks937bAo.db
DB_INSTALLS += $(MKS937B)/db/dbMks937bBi.db
DB_INSTALLS += $(MKS937B)/db/dbMks937bBo.db
DB_INSTALLS += $(MKS937B)/db/dbMks937bMbbi.db
DB_INSTALLS += $(MKS937B)/db/dbMks937bMbbo.db
DB_INSTALLS += dbMks937bAi_novar.db
DB_INSTALLS += dbMks937bAo_novar.db
DB_INSTALLS += dbMks937bBi_novar.db
DB_INSTALLS += dbMks937bBo_novar.db
DB_INSTALLS += dbMks937bMbbi_novar.db
DB_INSTALLS += dbMks937bMbbo_novar.db
DB_INSTALLS += $(COMBIVACCM52)/protocol/combivacCM52.db
DB_INSTALLS += $(COMBIVACCM52)/protocol/combivacCM52.proto


# Install Database to support reading the status of the autosave package:
DB_INSTALLS += $(AUTOSAVE)/db/save_restoreStatus.db

# =======================================================================

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

