TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devTilt.db
DB_INSTALLS += $(ASYN)/db/asynRecord.db
DB_INSTALLS += $(TOP)/tiltSup/devTilt.proto

#=======================================
include $(TOP)/configure/RULES
