TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devE5GN.db
DB_INSTALLS += $(ASYN)/db/asynRecord.db
DB_INSTALLS += $(TOP)/E5GNSup/devE5GN.proto

#=======================================
include $(TOP)/configure/RULES
